version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./public-html:/usr/local/apache2/htdocs/
        ports:
            - "8080:80"
